replicaCount: 1

image:
  repository: registry.example.com/mcp-suse # CHANGE THIS TO YOUR REPO
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: ClusterIP
  port: 80

storage:
  enabled: false
  size: 1Gi
  storageClass: ""
  mountPath: "/app/data"

env:
  mcpServerName: "Rancher-MCP"
